### ISSUE TITLE
3.0.9版本调用getTempKeys方法报错 QCloud\COSSTS\Exception not found

### ISSUE THREAD

**Issue by alpha1130** [tencentyun/qcloud-cos-sts-php-sdk#3]
Sts.php 行69, 81
抛出的Exception命名空间不正确，导致调用出错

<img width="299" alt="image" src="https://github.com/tencentyun/qcloud-cos-sts-php-sdk/assets/4863634/ad307d87-7dc0-4c44-a4cf-abcb70ae4282">

**Comment by tuuna** [comment]
我们修改一下

**Comment by tuuna** [comment]
已经在3.0.10版本都修复了:smile
