### ISSUE TITLE
error: foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by 894480109** [tencentyun/qcloud-cos-sts-php-sdk#6]
Sts.php 72行 foreach($config['allowPrefix'] as &$val)  allowPrefix是字符串吧，怎么会foreach呢？

qcloud_sts/qcloud-sts-sdk版本 3.0.10
php版本 8.0.25

**Comment by tuuna** [comment]
https://github.com/tencentyun/qcloud-cos-sts-sdk/blob/master/php/demo/sts_test.php

目前是支持传数组了哈
